# Generated by Django 4.2.4 on 2023-09-05 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_alter_postmodel_options_alter_postmodel_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='delete',
            field=models.DateTimeField(auto_now=True, verbose_name='delete'),
        ),
        migrations.AddField(
            model_name='postmodel',
            name='update',
            field=models.DateTimeField(auto_now=True, verbose_name='update'),
        ),
    ]
