# Generated by Django 4.2.4 on 2023-09-05 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_postmodel_delete_postmodel_update'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmodel',
            name='delete',
        ),
        migrations.RemoveField(
            model_name='postmodel',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='postmodel',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='postmodel',
            name='update',
        ),
        migrations.RemoveField(
            model_name='postmodel',
            name='update_at',
        ),
    ]
