# Generated by Django 4.2.4 on 2023-09-05 18:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_remove_postmodel_delete_remove_postmodel_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='update_at',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='update_at'),
        ),
    ]
