# Generated by Django 4.2.4 on 2023-09-10 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_commentmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentmodel',
            options={'verbose_name': 'comment', 'verbose_name_plural': 'comments'},
        ),
        migrations.AlterModelTable(
            name='commentmodel',
            table='comment-model',
        ),
    ]
