# Generated by Django 4.2.4 on 2023-09-12 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_alter_commentmodel_options_alter_commentmodel_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='body',
            field=models.TextField(max_length=500),
        ),
    ]
