# Generated by Django 4.2.4 on 2023-09-13 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0011_alter_postmodel_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecycleComment',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('post.commentmodel',),
        ),
        migrations.CreateModel(
            name='RecyclePost',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('post.postmodel',),
        ),
        migrations.AlterField(
            model_name='commentmodel',
            name='is_reply',
            field=models.BooleanField(default=True),
        ),
    ]
