# Generated by Django 4.2.5 on 2023-09-17 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0013_relationpostmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmodel',
            name='update_at',
        ),
    ]
