# Generated by Django 4.2.5 on 2023-09-17 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0016_alter_postmodel_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StatusPost',
        ),
        migrations.AddField(
            model_name='postmodel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
