# Generated by Django 4.2.5 on 2023-09-17 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0017_delete_statuspost_postmodel_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagPostModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'tag post',
                'verbose_name_plural': 'tag posts',
                'db_table': 'tag-post-model',
            },
        ),
        migrations.AddField(
            model_name='postmodel',
            name='post_tag',
            field=models.ManyToManyField(to='post.tagpostmodel'),
        ),
    ]
