# Generated by Django 4.2.5 on 2023-09-17 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0018_tagpostmodel_postmodel_post_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='post_tag',
            field=models.ManyToManyField(blank=True, related_name='Ptag', to='post.tagpostmodel'),
        ),
    ]
