# Generated by Django 4.2.5 on 2023-09-18 22:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0019_alter_postmodel_post_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmodel',
            name='image',
        ),
        migrations.RemoveField(
            model_name='postmodel',
            name='location',
        ),
        migrations.RemoveField(
            model_name='postmodel',
            name='video',
        ),
        migrations.RemoveField(
            model_name='relationpostmodel',
            name='dislike',
        ),
        migrations.AddField(
            model_name='commentmodel',
            name='update_at',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='update_at'),
        ),
        migrations.AddField(
            model_name='postmodel',
            name='update_at',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='update_at'),
        ),
        migrations.CreateModel(
            name='PostOptionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to='post/image')),
                ('video', models.FileField(blank=True, null=True, upload_to='post/video')),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='post.postmodel')),
            ],
            options={
                'verbose_name': 'PostModel',
                'verbose_name_plural': 'PostModels',
                'db_table': 'post-option-models',
            },
        ),
        migrations.CreateModel(
            name='CommentsOptionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to='post/image')),
                ('video', models.FileField(blank=True, null=True, upload_to='post/video')),
                ('comment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='post.postmodel')),
            ],
            options={
                'verbose_name': 'CommentOption',
                'verbose_name_plural': 'CommentOptions',
                'db_table': 'comment-option-model',
            },
        ),
    ]
