# Generated by Django 4.2.5 on 2023-09-18 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0020_remove_postmodel_image_remove_postmodel_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='slug',
            field=models.SlugField(),
        ),
    ]
