# Generated by Django 4.2.5 on 2023-09-19 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0021_alter_postmodel_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postoptionmodel',
            options={'verbose_name': 'PostOptionModel', 'verbose_name_plural': 'PostOptionModels'},
        ),
    ]
