# Generated by Django 4.2.5 on 2023-09-19 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0022_alter_postoptionmodel_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentmodel',
            name='update_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='update_at'),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='update_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='update_at'),
        ),
    ]
