# Generated by Django 4.2.4 on 2023-09-02 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=100, unique=True, verbose_name='Username')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email')),
                ('full_name', models.CharField(max_length=255, verbose_name='Full name')),
                ('mobile_phone', models.BooleanField(max_length=11, unique=True, verbose_name='Mobile')),
                ('birthday', models.DateField(auto_now=True, verbose_name='Birthday')),
                ('profile_image', models.ImageField(upload_to='images/profile', verbose_name='Profile')),
                ('banner_image', models.ImageField(upload_to='images/banner_profile', verbose_name='Profile')),
                ('is_admin', models.BooleanField(default=False, verbose_name='is admin')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='is superuser')),
                ('gender_choose', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=6, verbose_name='Gender')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'db_table': 'users-model',
            },
        ),
    ]
