# Generated by Django 4.2.4 on 2023-09-05 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_create_at_alter_user_deleted_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_deleted',
        ),
        migrations.AddField(
            model_name='user',
            name='update',
            field=models.DateTimeField(auto_now=True, verbose_name='update'),
        ),
    ]
