# Generated by Django 4.2.4 on 2023-09-05 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_user_deleted_at_remove_user_is_deleted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='update',
        ),
    ]
