# Generated by Django 4.2.4 on 2023-09-09 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_relationusermoel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RelationUserMoel',
            new_name='RelationUserModel',
        ),
        migrations.AlterModelOptions(
            name='relationusermodel',
            options={'verbose_name': 'relation', 'verbose_name_plural': 'relations'},
        ),
        migrations.AlterModelTable(
            name='relationusermodel',
            table='relation-model',
        ),
    ]
