# Generated by Django 4.2.4 on 2023-09-13 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_rename_relationusermoel_relationusermodel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='banner_image',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile_image',
        ),
    ]
