# Generated by Django 4.2.4 on 2023-09-13 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_user_banner_image_remove_user_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='update_at',
        ),
    ]
