# Generated by Django 4.2.4 on 2023-09-13 14:27

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_user_deleted_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReclceUser',
        ),
        migrations.CreateModel(
            name='RecycleUser',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.user',),
            managers=[
                ('deleted', django.db.models.manager.Manager()),
            ],
        ),
    ]
