# Generated by Django 4.2.5 on 2023-09-16 11:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_delete_reclceuser_recycleuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='create_at')),
                ('body', models.TextField(verbose_name='body notification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Unotification', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'notification-model',
                'verbose_name_plural': 'notifications-models',
                'db_table': 'notofication-model',
            },
        ),
    ]
