# Generated by Django 4.2.5 on 2023-09-18 22:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_notificationmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_deleted',
        ),
        migrations.AddField(
            model_name='user',
            name='update_at',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='update_at'),
        ),
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Birth day'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender_choose',
            field=models.CharField(choices=[('1', 'male'), ('2', 'female')], max_length=1, verbose_name='Gender'),
        ),
        migrations.CreateModel(
            name='Imageuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='create_at')),
                ('image', models.FileField(upload_to='profile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'image user',
                'verbose_name_plural': 'image users',
                'db_table': 'image_user_model',
            },
        ),
    ]
