# Generated by Django 4.2.5 on 2023-09-19 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_remove_user_deleted_at_remove_user_is_deleted_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtpCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_active_code', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile_phone', models.CharField(blank=True, max_length=11, unique=True, verbose_name='mobile')),
            ],
            options={
                'verbose_name': 'otp-code',
                'verbose_name_plural': 'otp-codes',
                'db_table': 'otp-code-model',
            },
        ),
    ]
