# Generated by Django 4.2.5 on 2023-09-19 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_otpcode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OtpCode',
        ),
        migrations.AlterField(
            model_name='imageuser',
            name='image',
            field=models.ImageField(upload_to='profile'),
        ),
    ]
