# Generated by Django 4.2.5 on 2023-09-19 12:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_delete_otpcode_alter_imageuser_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtpCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile_phone', models.CharField(blank=True, max_length=11, unique=True, verbose_name='mobile')),
                ('active_code', models.PositiveIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'otp-code',
                'verbose_name_plural': 'otp-codes',
                'db_table': 'otp-code-model',
            },
        ),
    ]
