# Generated by Django 4.2.5 on 2023-09-19 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_otpcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='update_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='update_at'),
        ),
    ]
