# Generated by Django 4.2.5 on 2023-09-19 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_alter_user_update_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpcode',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='create_at'),
        ),
    ]
