# Generated by Django 4.2.5 on 2023-09-19 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_otpcode_create_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otpcode',
            name='mobile_phone',
        ),
        migrations.RemoveField(
            model_name='otpcode',
            name='user',
        ),
    ]
